name: Unit Tests
on:
  workflow_call:
jobs:
  test:
    name: Test with Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test:unit
